"use strict";
/* =========================================================================
   PotionData.js - 약병 데이터 전용 파일
   - 약병은 이 파일의 POTION_DB만 수정하면 상점/보상/가방/전투 사용에 반영됩니다.
   - effect는 script.js의 기존 약병 처리 로직에서 지원하는 범위만 실행됩니다.
   ========================================================================= */

var POTION_SLOT_LIMIT = 3;

var POTION_DB = [
  { id:"cheongsim_pill", dataId:"IT001", name:"청심환", emoji:"💊", type:"heal", effect:"healPlayerHp", value:12, target:"player", rarity:"common", price:35, shopPrice:35, dropWeight:3, obtainFrom:["battle","shop","event"], implemented:true, desc:"정신력을 12 회복합니다.", fx:[{ t:"heal", v:12 }] },
  { id:"focus_talisman", dataId:"IT002", name:"집중부", emoji:"🔖", type:"energy", effect:"gainEnergy", value:1, target:"player", rarity:"common", price:30, shopPrice:30, dropWeight:3, obtainFrom:["battle","shop","event"], implemented:true, desc:"이번 턴 신통력을 1 회복합니다.", fx:[{ t:"energy", v:1 }] },
  { id:"protective_talisman", dataId:"IT003", name:"호신부", emoji:"🧿", type:"block", effect:"gainBlock", value:12, target:"player", rarity:"common", price:35, shopPrice:35, dropWeight:3, obtainFrom:["battle","shop","event"], implemented:true, desc:"마음의 결계를 12 얻습니다.", fx:[{ t:"block", v:12 }] },
  { id:"five_direction_water", dataId:"IT004", name:"오방수", emoji:"🌊", type:"blockCleanse", effect:"blockAndRemoveAgitation", value:8, removeWeak:1, target:"player", rarity:"common", price:40, shopPrice:40, dropWeight:3, obtainFrom:["battle","shop","event"], implemented:true, desc:"마음의 결계를 8 얻고 플레이어의 동요를 1 제거합니다.", fx:[{ t:"block", v:8 }, { t:"removeWeak", v:1 }] },
  { id:"lotus_incense", dataId:"IT005", name:"연꽃 향", emoji:"🪷", type:"applyMark", effect:"applyMark", value:2, target:"enemy", rarity:"common", price:40, shopPrice:40, dropWeight:3, obtainFrom:["battle","shop","event"], implemented:true, desc:"대상에게 성불 표식을 2 부여합니다.", fx:[{ t:"applyMark", v:2 }] },
  { id:"unsaid_letter", dataId:"IT006", name:"말하지 못한 편지", emoji:"💌", type:"applyRecollection", effect:"applyRecollection", value:3, target:"enemy", rarity:"common", price:40, shopPrice:40, dropWeight:0, obtainFrom:[], implemented:true, desc:"대상에게 회상 3을 부여합니다.", fx:[{ t:"applyRecollection", v:3 }] },
  { id:"warding_salt", dataId:"IT007", name:"액막이 소금", emoji:"🧂", type:"attackSingle", effect:"purifyTarget", value:12, target:"enemy", rarity:"common", price:40, shopPrice:40, dropWeight:3, obtainFrom:["battle","shop","event"], implemented:true, desc:"대상의 미련을 12 정화합니다.", fx:[{ t:"attackSingle", v:12 }] },
  { id:"salpuri_ash", dataId:"IT008", name:"살풀이 재", emoji:"⚱️", type:"attackAll", effect:"purifyAll", value:6, target:"enemy", rarity:"common", price:45, shopPrice:45, dropWeight:3, obtainFrom:["battle","shop","event"], implemented:true, desc:"모든 유령의 미련을 6 정화합니다.", fx:[{ t:"attackAll", v:6 }] },
  { id:"cracked_mirror_water", dataId:"IT009", name:"금이 간 경면수", emoji:"🪞", type:"applyFracture", effect:"applyFracture", value:2, target:"enemy", rarity:"common", price:45, shopPrice:45, dropWeight:0, obtainFrom:[], implemented:true, desc:"대상에게 균열 2를 부여합니다.", fx:[{ t:"applyFracture", v:2 }] },
  { id:"candlewax_seal_liquid", dataId:"IT010", name:"촛농 봉인액", emoji:"🕯️", type:"applyMarkAll", effect:"applyMarkAll", value:1, target:"enemy", rarity:"common", price:45, shopPrice:45, dropWeight:0, obtainFrom:[], implemented:true, desc:"모든 유령에게 성불 표식을 1 부여합니다.", fx:[{ t:"applyMarkAll", v:1 }] },
  { id:"memory_dew", dataId:"IT011", name:"기억 이슬", emoji:"💠", type:"applyRecollectionDraw", effect:"applyRecollectionDraw", value:1, target:"enemy", rarity:"common", price:45, shopPrice:45, dropWeight:0, obtainFrom:[], implemented:true, desc:"대상에게 회상 1을 부여하고 주문을 1장 뽑습니다.", fx:[{ t:"applyRecollection", v:1 }, { t:"draw", v:1 }] },
  { id:"clear_rice_water", dataId:"IT012", name:"맑은 쌀물", emoji:"🍚", type:"removePlayerStatus", effect:"removePlayerStatus", value:1, target:"player", rarity:"common", price:35, shopPrice:35, dropWeight:0, obtainFrom:[], implemented:false, desc:"플레이어의 불안 1과 무기력 1을 제거합니다.", fx:[{ t:"removePlayerStatus", status:"anxiety", v:1 }, { t:"removePlayerStatus", status:"lethargy", v:1 }] },
  { id:"peach_spring_water", dataId:"IT013", name:"복숭아 약수", emoji:"🍑", type:"healBlock", effect:"healAndBlock", value:6, target:"player", rarity:"common", price:45, shopPrice:45, dropWeight:0, obtainFrom:[], implemented:true, desc:"정신력을 6 회복하고 마음의 결계를 6 얻습니다.", fx:[{ t:"heal", v:6 }, { t:"block", v:6 }] },
  { id:"dawn_spring_water", dataId:"IT014", name:"새벽 샘물", emoji:"🌅", type:"drawThenDiscardChoice", effect:"drawThenDiscardChoice", value:2, target:"player", rarity:"common", price:40, shopPrice:40, dropWeight:0, obtainFrom:[], implemented:false, desc:"주문을 2장 뽑고 이후 손패 1장을 선택해 버립니다.", fx:[{ t:"drawThenDiscardChoice", draw:2, discard:1 }] },
  { id:"sealing_ink", dataId:"IT015", name:"봉인 먹물", emoji:"🖋️", type:"nextHighCostCardCostDown", effect:"nextHighCostCardCostDown", value:1, target:"player", rarity:"common", price:45, shopPrice:45, dropWeight:0, obtainFrom:[], implemented:false, desc:"이번 턴 다음에 사용하는 비용 2 이상 주문의 비용을 1 감소시키고 주문을 1장 뽑습니다. 최소 비용 0.", fx:[{ t:"nextHighCostCardCostDown", minCost:2, v:1, minResultCost:0 }, { t:"draw", v:1 }] },
  { id:"sutra_ash_water", dataId:"IT016", name:"경문 잿물", emoji:"📜", type:"exhaustStatusCardFromHandOrDraw", effect:"exhaustStatusCardFromHandOrDraw", value:1, target:"player", rarity:"common", price:35, shopPrice:35, dropWeight:0, obtainFrom:[], implemented:false, desc:"손패의 상태 주문 1장을 선택해 소멸합니다. 상태 주문이 없다면 주문을 1장 뽑습니다.", fx:[{ t:"exhaustStatusCardFromHandOrDraw", exhaust:1, drawIfNone:1 }] },
  { id:"blank_talisman", dataId:"IT017", name:"백지 부적", emoji:"📄", type:"nextTurnDraw", effect:"nextTurnDraw", value:2, target:"player", rarity:"common", price:40, shopPrice:40, dropWeight:0, obtainFrom:[], implemented:false, desc:"다음 턴 시작 시 주문을 2장 추가로 뽑습니다.", fx:[{ t:"nextTurnDraw", v:2 }] },
  { id:"white_salt_line", dataId:"IT018", name:"흰 소금선", emoji:"▫️", type:"removeEnemyBlock", effect:"removeEnemyBlock", value:12, target:"enemy", rarity:"common", price:35, shopPrice:35, dropWeight:0, obtainFrom:[], implemented:false, desc:"대상 유령의 결계를 최대 12 제거합니다.", fx:[{ t:"removeEnemyBlock", v:12 }] },
  { id:"small_bell_liquor", dataId:"IT019", name:"작은 방울술", emoji:"🍶", type:"createBellStrikeDraw", effect:"createBellStrikeDraw", value:1, target:"player", rarity:"common", price:40, shopPrice:40, dropWeight:0, obtainFrom:[], implemented:false, desc:"방울치기 1장을 생성하고 주문을 1장 뽑습니다.", fx:[{ t:"createBellStrike", v:1 }, { t:"draw", v:1 }] },
  { id:"spirit_eye_water", dataId:"IT020", name:"영안수", emoji:"👁️", type:"draw", effect:"drawCards", value:3, target:"player", rarity:"uncommon", price:55, shopPrice:55, dropWeight:2, obtainFrom:["battle","shop","event"], implemented:true, desc:"주문을 3장 뽑습니다.", fx:[{ t:"draw", v:3 }] },
  { id:"samsin_water", dataId:"IT021", name:"삼신수", emoji:"🌿", type:"cleanseAllPlayerDebuffs", effect:"healAndCleanseAllPlayerDebuffs", value:12, target:"player", rarity:"uncommon", price:65, shopPrice:65, dropWeight:0, obtainFrom:[], implemented:false, desc:"정신력을 12 회복하고 플레이어의 해로운 상태를 전부 제거합니다.", fx:[{ t:"heal", v:12 }, { t:"cleanseAllPlayerDebuffs" }] },
  { id:"white_tiger_water", dataId:"IT022", name:"백호수", emoji:"🐯", type:"energy", effect:"gainEnergy", value:2, target:"player", rarity:"uncommon", price:65, shopPrice:65, dropWeight:2, obtainFrom:["battle","shop","event"], implemented:true, desc:"이번 턴 신통력을 2 회복합니다.", fx:[{ t:"energy", v:2 }] },
  { id:"goblin_mirror_water", dataId:"IT023", name:"도깨비 거울물", emoji:"🪞", type:"discardAnyThenDrawSameCount", effect:"discardAnyThenDrawSameCount", value:0, target:"player", rarity:"uncommon", price:60, shopPrice:60, dropWeight:0, obtainFrom:[], implemented:false, desc:"손패에서 원하는 만큼 주문을 선택해 버리고, 버린 수만큼 다시 뽑습니다.", fx:[{ t:"discardAnyThenDrawSameCount" }] },
  { id:"diamond_water", dataId:"IT024", name:"금강수", emoji:"💎", type:"blockGainMultiplierThisTurn", effect:"blockGainMultiplierThisTurn", value:1.5, target:"player", rarity:"uncommon", price:65, shopPrice:65, dropWeight:0, obtainFrom:[], implemented:false, desc:"이번 턴 획득하는 마음의 결계량이 50% 증가합니다.", fx:[{ t:"blockGainMultiplierThisTurn", v:1.5 }] },
  { id:"soul_return_water", dataId:"IT025", name:"회혼수", emoji:"🫧", type:"recoverHandDiscard", effect:"recoverHandDiscard", value:1, target:"player", rarity:"uncommon", price:70, shopPrice:70, dropWeight:0, obtainFrom:[], implemented:false, desc:"이번 전투에서 가장 최근에 손패에서 버린 주문 1장을 회수하고 해당 주문의 비용을 이번 턴 1 감소시킵니다. 최소 비용 0.", fx:[{ t:"recoverHandDiscard", costReduce:1, minResultCost:0, excludeDiscardedAfterUse:true }] },
  { id:"grudge_ink", dataId:"IT026", name:"응어리 먹물", emoji:"⚫", type:"discardDrawTriggerGrowth", effect:"discardDrawTriggerGrowth", value:2, target:"player", rarity:"uncommon", price:60, shopPrice:60, dropWeight:0, obtainFrom:[], implemented:false, desc:"손패 1장을 버리고 주문을 2장 뽑습니다. 버린 주문이 한풀이 계열이면 해당 성장 효과를 1회 발동합니다.", fx:[{ t:"discardDrawTriggerGrowth", discard:1, draw:2, archetype:"hanpuri", growthTrigger:1 }] },
  { id:"divine_excitation_liquor", dataId:"IT027", name:"신명주", emoji:"🔔", type:"createBellStrikeBonus", effect:"createBellStrikeBonus", value:2, target:"player", rarity:"uncommon", price:60, shopPrice:60, dropWeight:0, obtainFrom:[], implemented:false, desc:"방울치기 2장을 생성하고 이번 턴 방울치기의 정화량이 1 증가합니다.", fx:[{ t:"createBellStrike", v:2 }, { t:"bellStrikePurifyBonusThisTurn", v:1 }] },
  { id:"ghost_gate_talisman", dataId:"IT028", name:"귀문부", emoji:"符", type:"nextAttackDouble", effect:"nextAttackMultiplier", value:1.5, target:"player", rarity:"rare", price:90, shopPrice:90, dropWeight:1, obtainFrom:["battle","shop","event"], implemented:true, desc:"이번 턴 다음 공격 주문의 총 정화량이 50% 증가합니다.", fx:[{ t:"nextAttackDouble", v:1.5 }] },
  { id:"manshin_call", dataId:"IT029", name:"만신의 부름", emoji:"📣", type:"createTemporaryCopy", effect:"createTemporaryCopy", value:1, target:"player", rarity:"rare", price:95, shopPrice:95, dropWeight:0, obtainFrom:[], implemented:false, desc:"다음에 사용하는 주문 사용 후 해당 주문의 임시 복사본 1장을 손패에 생성합니다. 복사본 비용은 원래 비용과 동일하며 턴 종료 시 소멸합니다.", fx:[{ t:"createTemporaryCopy", keepOriginalCost:true, exhaustAtTurnEnd:true }] },
  { id:"goblin_panacea_bottle", dataId:"IT030", name:"도깨비 만병", emoji:"🧪", type:"fillEmptyPotionSlots", effect:"fillEmptyPotionSlots", value:2, target:"player", rarity:"rare", price:90, shopPrice:90, dropWeight:0, obtainFrom:[], implemented:false, desc:"사용 후 빈 약병 슬롯을 최대 2칸까지 일반 또는 희귀 약병으로 채웁니다.", fx:[{ t:"fillEmptyPotionSlots", maxSlots:2, rarityWeights:{ common:75, uncommon:25 }, allowRare:false, excludeSelf:true, noDuplicateInSameUse:true, removeSelfFirst:true }] }
];

window.POTION_SLOT_LIMIT = POTION_SLOT_LIMIT;
window.POTION_DB = POTION_DB;
